version: "1.0"

services:
  db:
    container_name: postgres
    image: postgres:14-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    container_name: nginx
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/tamriel/static
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data_prod:
  static_volume:
