version: "3.8"

services:
  web:
    container_name: python
    build: ./services/web
    command: python main.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: postgres-2
    image: postgres:14-alpine
    #ports:
    #  - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=angelova
      - POSTGRES_PASSWORD=angelova
      - POSTGRES_DB=tamriel_db

volumes:
  postgres_data:
